### ISSUE TITLE
Support gcc __attribute__((__packed__))

### ISSUE THREAD

**Issue by GoogleCodeExporter** [davidjamesca/ctypesgen#46]
```
This tool works like a charm, my only issue is that packed data structures does 
not get recognised.

The .c file:
struct __attribute__((__packed__)) {

Should become:

class struct_something(Structure):
    __pack__ = 1
    pass

In the .py file. Ctypes already have support for this. So i guess it's a simple 
matter of finding the attribute in the parser.
```

Original issue reported on code.google.com by `johan.de...@gmail.com` on 10 Oct 2013 at 1:26

**Comment by johandc** [comment]
I would like to bump this issue, again. We still need it very much.

**Comment by nickaknudson** [comment]
Just pass `--cpp 'gcc -E "-D__attribute__(x)="'` to `ctypesgen.py`

This will redefine `__attribute__(x)` to be blank and then ctypesgen will ignore it.

**Comment by johandc** [comment]
That’s the problem: attribute packed should NOT be ignored.
So the parser needs to understand it and insert __pack__ = 1 in the ctypes output.

Regards,
Johan.

From: "Nick Knudson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just pass --cpp 'gcc -E "-D__attribute__(x)="' to ctypesgen.py

This will redefine __attribute__(x) to be blank and then ctypesgen will ignore it.

—
Reply to this email directly or view it on GitHub<https://github.com/davidjamesca/ctypesgen/issues/46#issuecomment-157552540>.


--
Johan de Claville Christiansen
Software Architect & RF Engineer

GomSpace
www.gomspace.com<http://www.gomspace.com/>
Office: +45 96356111
CVR: 30899849

**Comment by techtonik** [comment]
@Alan-R thanks. Nice to see this project is alive.
