### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by davidjamesca** [davidjamesca/ctypesgen#51]
Request from r-ku: "Can you please merge the code in https://github.com/r-ku/ctypesgen with trunk and update the pypi? -- It generates Python3 compatible code and would be greatly helpful!"

r-ku: I've posted some feedback on your branch. Can you address the feedback?

**Comment by epifanio** [comment]
Anyone working on a py3 version of ctypesgen?

**Comment by olsonse** [comment]
ctypesgen is now Py3 compatible
