### ISSUE TITLE
status of ctypesgen

### ISSUE THREAD

**Issue by jhamman** [davidjamesca/ctypesgen#52]
Can you give a brief summary of where you see this project going in the future?  I'm trying to decide if we can use the package in one of our projects.
- Do you have any further development plans for `ctypesgen`?
- How about developing some formal documentation?
- There are a number of issues that seem to have been migrated from the google code site, are they all outstanding issues?  If so, do you have plans to address any of them?
- How about integration with `setuptools`?  It would be really nice if there was a clear example of how you could build extensions using `setuptools`, develop `ctypes` bindings linked to the extensions using `ctypesgen`, then install the full package.
- PEP8.  The generated code is a bit rough to read.  Could a) we clean up the syntax of the code or b) we bind something like [`autopep8`](https://pypi.python.org/pypi/autopep8/) to the module to create cleaner looking code?
- Testing.  There are a few tests in the test directory but there is a lot of room for improvement here.  How about adopting a unit testing framework like [`pytest`](http://pytest.org/latest/)?
- Python 3.  There is already an open issue for this on #51 but its worth mentioning again.

**Comment by jhamman** [comment]
bump...?

cc @aaiyer, @karelin, @pombreda, @pombredanne, and @vanem

**Comment by techtonik** [comment]
I am not sure that ctypegen folks are active on Github. ctypes also became less actual with CFFI on the horizon, but it ctypes one major advantage that it doesn't need anything installed. Try to full some PR to see how it goes.

**Comment by jhamman** [comment]
Thanks @techtonik.  I'll look into the `CFFI` option a bit more.  If that doesn't become a viable option, I may start working on `ctypesgen`.

**Comment by maedoc** [comment]
@davidjamesca @jhamman is there any news here? I'd also like to use (and update for Py 3 compat) ctypesgen as it works nicely. In particular the JSON output is useful for developing bindings for other languages, so it'd be a shame to see this lib subject to bitrot.

**Comment by techtonik** [comment]
My guess that the best way to avoid parser to JSON from being bitrotten is to fork and rename it into separate project. Because `ctypes` part on the name kind of fails smoke test on freshness.

**Comment by jhamman** [comment]
@maedoc - no updates from me.  I moved on to use [`cffi`](http://cffi.readthedocs.org/).

**Comment by olsonse** [comment]
Thought I'd mention--I've been using this for a while and have updated several things on this project.  I'll keep updating things and taking pull-requests.

**Comment by rradjabi** [comment]
@olsonse I'm trying to use your fork of ctypesgen and I could use a little help with the demo. If I'm starting with demo.c, demo.h, and demoapp.c, what are the steps to run this example?

Thanks,
Ryan

**Comment by olsonse** [comment]
@rradjabi I just added a README.md to the demo directory that might be able to help you.  This is a really old demo and ultra non-complicated.  Although it is not complicated, the procedure for creating bindings for a more complicated library/header file is quite the same process (just run ctypesgen with the appropriate headers and shared libraries).  You should notice that ctypesgen inserts a little line at the top of the files that it generates so you can see how to regenerate the file.

**Comment by olsonse** [comment]
Several of us have been keeping this updated on separate branches and with more collaborators being added to the original project (the GitHub version).  Closing this issue as development has actually become more coordinated recently...

**Comment by pombredanne** [comment]
@olsonse Thanks!

**Comment by techtonik** [comment]
Awesome. =)
