### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by mentaal** [davidjamesca/ctypesgen#53]
Hi there, 
I am trying to use your package. 
I am using python 3 from within Anaconda. 

What I did:
1) Cloned repo
2) Checked out python-3 branch
3) Ran: 2to3 -w . (there were still some python2 print statements etc)
4) Ran python ctypesgen.py -h which yielded the following:

> python ctypesgen.py -h
> Traceback (most recent call last):
>   File "c:\ctypesgen\ctypesgencore\parser\lex.py", line 39, in <module>
>     _INSTANCETYPE = (types.InstanceType, object)
> AttributeError: 'module' object has no attribute 'InstanceType'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "ctypesgen.py", line 36, in <module>
>     import ctypesgencore
>   File "c:\ctypesgen\ctypesgencore\__init__.py", line 51, in <module>
>     from . import parser
>   File "c:\ctypesgen\ctypesgencore\parser\__init__.py", line 17, in <module>
>     from .datacollectingparser import DataCollectingParser
>   File "c:\ctypesgen\ctypesgencore\parser\datacollectingparser.py", line 10, in <module>
>     from . import ctypesparser
>   File "c:\ctypesgen\ctypesgencore\parser\ctypesparser.py", line 15, in <module>
>     from .cparser import CParser
>   File "c:\ctypesgen\ctypesgencore\parser\cparser.py", line 19, in <module>
>     from . import preprocessor
>   File "c:\ctypesgen\ctypesgencore\parser\preprocessor.py", line 15, in <module>
>     from . import lex, yacc
>   File "c:\ctypesgen\ctypesgencore\parser\lex.py", line 41, in <module>
>     _INSTANCETYPE = types.InstanceType
> AttributeError: 'module' object has no attribute 'InstanceType'

**Comment by jhamman** [comment]
@mentaal - I'd recommend checking out #52.  I ended up going the CFFI route and that seems to be working pretty well.  

The `2to3` route is not likely to apply since `ctypesgen` actually writes Python code and the `2to3` utility will probably miss a good portion of that logic.

**Comment by mentaal** [comment]
Thanks for the info @jhamman. I'll checkout CFFI. 
It just seems a pity as ctypes is what comes up in a search relating to python and dlls. Then the logical next step is ctypesgen.
