### ISSUE TITLE
pip install: `ImportError: No module named 'processor'`

### ISSUE THREAD

**Issue by altendky** [davidjamesca/ctypesgen#54]
Looks like you might need to add a dependency on `processor` in `setup.py`?

```
altendky@tp:/epc/t/307/st.hmi$ pip3 install ctypesgen
Collecting ctypesgen
  Downloading ctypesgen-0.r125.tar.gz (105kB)
    100% |████████████████████████████████| 112kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yln8qcnj/ctypesgen/setup.py", line 13, in <module>
        import ctypesgencore
      File "/tmp/pip-build-yln8qcnj/ctypesgen/ctypesgencore/__init__.py", line 56, in <module>
        import processor
    ImportError: No module named 'processor'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yln8qcnj/ctypesgen/
```

**Comment by altendky** [comment]
Also, `printer`, `descriptions`, ...

Hmm, wait.  It installed straight away with `pip2` so it may be more about Python3  compatibility than dependencies.

**Comment by martmists** [comment]
The root of the issue here is that python no longer supports using imports as relative imports this way, relative imports need to be prefixed with `.` or have the full path.

**Comment by scorp08** [comment]
I get nomodule named printer error. Are there a fix ?

**Comment by altendky** [comment]
@scorp08, with 4 years since the last commit I wouldn't plan on using this repo unless you want to maintain it.  Presumably there are better options.  Possibly built around cffi.

**Comment by scorp08** [comment]
@altendky at leat ıt seems like a relative import problem. Could not check detail of __init__ but there must be put `from . ` . But still no-luck. I would like to install brl-cad and ctypesgen is necessary for it.

**Comment by altendky** [comment]
@scorp08 does BRL-CAD really support py3 but depend on this py2-only library?  Are you sure you don't want one of the BRL-CAD installers?

**Comment by scorp08** [comment]
@altendky  I do not know if it is support. I can install via installers but in any case I want to integrate with python

**Comment by altendky** [comment]
@scorp08 the blind guess would be to use py2 rather than py3.  If that's not a solution then check with whatever package you are expecting to give you the BRL-CAD/Python integration and see what they say works.

**Comment by drsteve** [comment]
There's a well-maintained fork of ctypesgen over at (https://github.com/olsonse/ctypesgen). That fork is Python 3 compatible and is, as best I can tell, the *de facto* home for ctypesgen these days.

**Comment by altendky** [comment]
@drsteve, given the lack of maintenance here the fork might be able to take over the PyPI name.

**Comment by Alan-R** [comment]
This should be fixed by the 1.0.0 version.

**Comment by fahadmunir3326** [comment]
pip install processor 

use this command it will work

**Comment by gwbischof** [comment]
pip install processor 
will give you a totally different package that it also called processor
