### ISSUE TITLE
No tests that use the main program

### ISSUE THREAD

**Issue by Alan-R** [davidjamesca/ctypesgen#68]
So, if/when its hosed, we won't know...

**Comment by olsonse** [comment]
As indicated in the comments for #67, The actual code for the main script should remain part of the library and the installed version of "bin/ctypesgen" should come from the auto-generated entry point from the setup.py script.  

The "run.py" script is a decent work-alike that does call the same entry point [ctypesgen.main.main()] and could be run as a test of that entry point.  Would not be a bad idea to at least execute this function directly as a part of the testsuite, or perhaps call this function as a separate process.  Maybe it would be sufficient to simply pass in a few simple arguments, like "--version" for instance.
