### ISSUE TITLE
WinDLL vs CDLL method call

### ISSUE THREAD

**Issue by kpoman** [davidjamesca/ctypesgen#74]
Hello,
I built a wrapper with ctypesgen on Windows and got this error:
`
ValueError: Procedure called with not enough arguments (4 bytes missing) or wrong calling convention`

I then changed the WindowsLibrary to force usage of windll:

```
    def __init__(self, path):
        self.cdll = ctypes.windll.LoadLibrary(path) # ctypes.cdll.LoadLibrary(path)
        self.windll = ctypes.windll.LoadLibrary(path)
```
So apparently my dll is a WinDLL (calling convention). I wonder how can I call the .windll version of the methods without this hack. ftrScanAPI is my ctypesgenerated wrapper, and I call the methods as this:

```
dev = ftrScanAPI.ftrScanOpenDevice()
ret = ftrScanAPI.ftrScanCloseDevice(dev)

```

Thank you for any tips !

**Comment by olsonse** [comment]
So, perhaps the error has changed when trying to call libraries with CDLL convention when they should be using WinDLL convention?  I don't have a configuration setup right now for windows, but does the CDLL calling interface still actually find functions from a WinDLL library (and hence not throw the AttributeError that was expected in this case in __getattr__ in _WindowsLibrary)?

**Comment by kpoman** [comment]
> So, perhaps the error has changed when trying to call libraries with CDLL convention when they should be using WinDLL convention? I don't have a configuration setup right now for windows, but does the CDLL calling interface still actually find functions from a WinDLL library (and hence not throw the AttributeError that was expected in this case in **getattr** in _WindowsLibrary)?

The choice between de cdll and windll call is done automatically by the ctypesgenerated code, from what I see in the WindowsLibrary object:

```
    def __init__(self, path):
        self.cdll = ctypes.windll.LoadLibrary(path) #ctypes.cdll.LoadLibrary(path)
        self.windll = ctypes.windll.LoadLibrary(path)

    def __getattr__(self, name):
        try: return getattr(self.cdll,name)
        except AttributeError:
            try: return getattr(self.windll,name)
            except AttributeError:
                raise
```
Do I add some kind of print to see which getattr is triggering on my buggy calls ?

**Comment by olsonse** [comment]
Yes, but the choice currently depends on being able to even find a function first through the CDLL interface.  Perhaps you can manually try to load the library as a test:
----
import ctypes
cdll = ctypes.cddl.LoadLibrary('/path/to/library')
print("Using CDLL library load, we find: ", getattr(cdll, "name-of-desired-function"))
----

If this little test does not raise an exception when you do "getattr(cdll,'name-of-desired-function')", then we are going to need to find a different automatic way to select either the WinDLL or CDLL interface.  Based on your earlier report, I am guessing that this is exactly what the problem is and that we will have to determine a better way to automatically detect whether the library should use WinDLL or CDLL.  

Incidentally, which version of Python are you using?  Which install/distribution of Python on Windows?  Which Windows version?

**Comment by kpoman** [comment]
See below details:

```
python37-32\python.exe
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit
(Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> cdll = ctypes.cdll.LoadLibrary('ftrScanAPI.dll')
>>> print(getattr(cdll, 'ftrScanOpenDevice'))
<_FuncPtr object at 0x01383468>
>>> windll = ctypes.windll.LoadLibrary('ftrScanAPI.dll')
>>> print(getattr(cdll, 'ftrScanOpenDevice'))
<_FuncPtr object at 0x01383468>
>>>
```

**Comment by kpoman** [comment]
So basically both are working and the windll/cdll selectors of the generated file are not functional. Is there any other way to check for cdecl/stdcall compatibility of a dll ? Btw, it is correctly declared on the headers (WIN32 defined and setting the call convention to stdcall so something on the generator could at least get that info). I can add a switch to force usage of WinDLL, but there might be something better.
Btw, something curious is, even if I force from _WindowsLibrary both self.cdll and self.windll to be a windll, if I print type of any method, it related to CDLL refs.

**Comment by olsonse** [comment]
This is related to issue #72.  It seems that we should actually properly watch for stdcall declaration and use the WinDLL interface for a function that has it declared that way...  I don't see that ctypesgen ever supported stdcall.   There is at least one example of __attribute__ being supported (in the case of (packed)).  I think we could probably change things to support the stdcall attribute correctly and automatically setup a function to use the WinDLL interface on windows (otherwise defaulting to cdecl calling convention).

**Comment by kpoman** [comment]
> This is related to issue #72. It seems that we should actually properly watch for stdcall declaration and use the WinDLL interface for a function that has it declared that way... I don't see that ctypesgen ever supported stdcall. There is at least one example of **attribute** being supported (in the case of (packed)). I think we could probably change things to support the stdcall attribute correctly and automatically setup a function to use the WinDLL interface on windows (otherwise defaulting to cdecl calling convention).

Ok patch patch patch !!!! If you need a beer just let me know =P
Am gonna check if I can do some monkeypatch here for now ..

**Comment by kpoman** [comment]
Just to give more feedback: I am building an exe with pyinstaller from an app that uses many dll's, some cdll, some windll. There is no way to make ctypesgen right now chose a particular call convention. Also, the code that loads the Windows Library tries to do it with via _WindowsLibrary (which tries to take care of both cdll and windll) but if it fails (because the lib is not on the first path), goes to loading on other places without still taking care of cdll vs windll (aka, it forces the cdll interface):

>     def load_library(self, libname):
>         try:
>             result = LibraryLoader.load_library(self, libname)
>             print('cool loaded first')
>         except ImportError:
>             result = None
>             if os.path.sep not in libname:
>                 for name in self.name_formats:
>                     try:
>                         result = getattr(ctypes.**cdll**, name % libname)
>                         if result:
>                             break
>                     except WindowsError:
>                         result = None
>             if result is None:
>                 try:
>                     result = getattr(ctypes.**cdll**, libname)
>                 except WindowsError:
>                     result = None
>             if result is None:
>                 raise ImportError("%s not found." % libname)
>         return result

which in turn makes stuff like PyInstaller (that messes the dll paths) go back to the wrong convention.

**Comment by olsonse** [comment]
I need you to try out the new loader that is in the newest patches on my [gcc-attribs branch in olsonse/ctypesgen](/olsonse/ctypesgen/tree/gcc-attribs).  It should use a more uniform approach and should cycle through several names to try before it fails to load in this newer approach (but I don't currently have a windows install to test this with).
