### ISSUE TITLE
a path separator bug prevents ctypesgen running directly on windows

### ISSUE THREAD

**Issue by AllenLius** [davidjamesca/ctypesgen#75]
I'm using ctypesgen without Cygwin, and it failed to generate output file due to the regular expression below didn't match any preamble py file.

printer_python\printer.py:
```
def get_preamble(...)
        m = re.search("preamble/(\d)_(\d).py$", fp)
```
The slash(/) in the regular expression doesn't match any preamble file in Windows (preamble\2_5.py).

**Comment by AllenLius** [comment]
verified it using latest source and got an error below:
line 26, in get_preamble
    m = re.search(preamble_pattern, fp)
  File "C:\Python27_64\lib\re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "C:\Python27_64\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

**Comment by olsonse** [comment]
strange.  Just tried this with py27 and py3, both successful.  What is your version exactly?

**Comment by AllenLius** [comment]
v2.7.15:ca079a3ea3 64-bits
The code below seams work:
m = re.search("preamble\\\\(\d)_(\d).py$", fp)

**Comment by AllenLius** [comment]
I think this is enough because every 'fp' always starts with 'preamble':
`m = re.search("(\d)_(\d).py$", fp)`

**Comment by olsonse** [comment]
That is a good point.  I guess the windows path separator needs additional escaping anyway when used as a regular expression.

**Comment by olsonse** [comment]
Fixed (again)
