### ISSUE TITLE
Handle double typedef'd structs better.

### ISSUE THREAD

**Issue by carmiac** [davidjamesca/ctypesgen#81]
I have a third party closed source library that I am wrapping to python that ctypesgen doesn't handle well due to the typdef choices made by the library authors.

Specifically, all structs are defined in the following manner:

```C
typdef struct {
  int a;
  char b;
} FOO, *PFOO;
```

With functions that look like:
```C
void Foo_Func(PFOO pFoo);
````

ctypesgen then creates something like the following:
```python
class struct_anon_311(Structure):
    pass
FOO = struct_anon_311

class struct_anon_312(Structure):
    pass
PFOO = POINTER(struct_anon_312)
```
This is pretty unusable since there is no safe way to create a struct_anon_312 object, and the PFOO pointer won't accept a FOO object.

What ctypes should really do is:
```python
class struct_anon_311(Structure):
    pass
FOO = struct_anon_311
PFOO = POINTER(struct_anon_311)
```

**Comment by carmiac** [comment]
One note: It doesn't do this when the structs aren't anonymous.
So something like
```C
typdef foo_struct {
  int a;
  char b;
} FOO, *PFOO;
```
is handled correctly.

**Comment by olsonse** [comment]
Very interesting corner case.  Looking at it...
