### ISSUE TITLE
ctypesgen gives a warning because it cannot parse some macros

### ISSUE THREAD

**Issue by sumagnadas** [davidjamesca/ctypesgen#85]
i am trying to build python bindings from .h files
But it cant parse macros and the files are mainly made up of macros
the macros are like:
1. `#define VINITALL(_v) { ( _v ) , ( _v ) , ( _v ) }`
2. `#define HSWAP(_a,_b) do { fastf_t _t ; _t = ( _a ) [ X ] ; ( _a ) [ X ] = ( _b ) [ X ] ; ( _b ) [ X ] = _t ; _t = ( _a ) [ Y ] ; ( _a ) [ Y ] = ( _b ) [ Y ] ; ( _b ) [ Y ] = _t ; _t = ( _a ) [ Z ] ; ( _a ) [ Z ] = ( _b ) [ Z ] ; ( _b ) [ Z ] = _t ; _t = ( _a ) [ W ] ; ( _a ) [ W ] = ( _b ) [ W ] ; ( _b ) [ W ] = _t ; } while ( 0 )`

Many of header files contain macros like these and if it cannot parse those macros, then i cant access them.
I tried to write those myself in python but there are many of them and writing them up is not going to be easy so i need some help with this

#### System Information

Python version: 3.8
OS: Linux Ubuntu 20.04

Any help is appreciated.

**Comment by sumagnadas** [comment]
@olsonse @davidjamesca i need some help ASAP so i tagged you guys. sorry for that.

**Comment by Alan-R** [comment]
Please give a specific short example (like the one you gave) along with the output you got when you gave it to ctypesgen.

**Comment by Alan-R** [comment]
Ctypesgen cannot parse "normal" C code - anything more than an expression. This code is a good example of something ctypes (and hence ctypesgen) cannot do. It cannot interpret C code beyond simple expressions.

If you want to use this in ctypesgen, then you need to write a C function to use it, and then refer to the C function in your python program via ctypesgen/ctypes.
