### ISSUE TITLE
Tests fail on Python 3.8 and 3.9

### ISSUE THREAD

**Issue by Freed0mBear** [davidjamesca/ctypesgen#90]
ctypesgen builds fine on py3.8 and py3.9, but the tests fail:

OK
 * python3_8: running distutils-r1_run_phase python_test
....................................../var/tmp/portage/dev-python/ctypesgen-1.0.2/work/ctypesgen-ctypesgen-1.0.2/ctypesgen/test/../../temp.py:2861: SyntaxWarning: 'NoneType' object is not callable; perhaps you missed a comma?
  return (None (ord_if_char((((__FDS_BITS (set)) [(__FD_ELT (d))]) | (__FD_MASK (d)))))).value
/var/tmp/portage/dev-python/ctypesgen-1.0.2/work/ctypesgen-ctypesgen-1.0.2/ctypesgen/test/../../temp.py:2865: SyntaxWarning: 'NoneType' object is not callable; perhaps you missed a comma?
  return (None (ord_if_char((((__FDS_BITS (set)) [(__FD_ELT (d))]) & (~(__FD_MASK (d))))))).value
./var/tmp/portage/dev-python/ctypesgen-1.0.2/work/ctypesgen-ctypesgen-1.0.2/ctypesgen/test/../../temp.py:2861: SyntaxWarning: 'NoneType' object is not callable; perhaps you missed a comma?
  return (None (ord_if_char((((__FDS_BITS (set)) [(__FD_ELT (d))]) | (__FD_MASK (d)))))).value
/var/tmp/portage/dev-python/ctypesgen-1.0.2/work/ctypesgen-ctypesgen-1.0.2/ctypesgen/test/../../temp.py:2865: SyntaxWarning: 'NoneType' object is not callable; perhaps you missed a comma?
  return (None (ord_if_char((((__FDS_BITS (set)) [(__FD_ELT (d))]) & (~(__FD_MASK (d))))))).value
.......
----------------------------------------------------------------------
Ran 46 tests in 7.567s

[same for 3.9]

**Comment by Alan-R** [comment]
c

**Comment by Alan-R** [comment]
The version in source control currently passes tests on 2.7, 3.7, 3.8 and 3.9.  Please check that version and reopen this if it is still failing for you.
