### ISSUE TITLE
Upload (sdist) tarball to pypi with prebuilt version information

### ISSUE THREAD

**Issue by duncanmmacleod** [davidjamesca/ctypesgen#93]
I am interested in packaging this project for other systems, so am wondering if it is possible to have a publicly available source distribution (tarball) with pre-completed version information?

If I download the automatically-generated tarball from github release archives, the version information is broken because it tried to generate the `VERSION` file on-the-fly without git information to rely upon.

**Comment by Alan-R** [comment]
The version in source control now does this a different way. Please verify that the issue still exists (not release for this version yet).  Reopen if it still exists.
