### ISSUE TITLE
Need Help with parser error -> Syntax error at '\n'

### ISSUE THREAD

**Issue by bgh34056** [davidjamesca/ctypesgen#94]
@olsonse 

I am getting this error 

The code in question is 

**typedef unsigned long long Uint64;**

**#define CAST_TO_X_PTR    (Uint64)(unsigned long)**   --> error is in this line 

Can you please share your thoughts on how this syntax parsing can be fixed?

Thank in advance .

**Comment by Alan-R** [comment]
I suspect that this code is being interpreted as a macro with a parameter, when you didn't intend that.

**Comment by Alan-R** [comment]
One simple way would be to define it using a parameter like this:
```
#define CAST_TO_X_PTR(foo) ((Uint64)(unsigned long) (foo))
```
I suspect this would work.
